springdoc:
  api-docs:
    path: /api-docs  # api-docs 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/api-docs로 리다이렉션 됨.
  swagger-ui:
    path: /apis  # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.

    groups-order: DESC # path, query, body, response 순으로 출력

    tags-sorter: alpha # 태그를 알파벳 순으로 정렬

    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능

  paths-to-match:
    - /api/** # swagger-ui에 표시할 api 의 엔드포인트 패턴

  servers:
    - "http://localhost:8080${server.servlet.context-path}"
    - "https://api.conolja.site${server.servlet.context-path}"