spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://postgres:5432/conolja-dev
    username: conolja
    password: conolja123!@#


springdoc:
  servers:
    - "https://api.conolja.site${server.servlet.context-path}"
