spring:
  application:
    profiles:
      active: dev  # 어플리케이션의 프로파일 설정

  datasource:
    url: jdbc:postgresql://postgres:5432/conolja?currentSchema=conolja
    username: conolja
    password: conolja123!@#

springdoc:
  servers:
    - "https://api.conolja.site${server.servlet.context-path}"
